import type { ShopProduct, ShopCategory } from './shop-types';

// ─── Shop Categories ──────────────────────────────────────────────────────────
export const SHOP_CATEGORIES: ShopCategory[] = [
  {
    id: 'fermetures-nylon',
    slug: 'fermetures-nylon',
    name: 'Fermetures Nylon',
    description: 'Fermetures éclair en nylon de qualité supérieure — toutes tailles et couleurs',
    icon: '🔒',
    color: '#3B82F6',
    image: '/fermetures.jpg',
  },
  {
    id: 'fermetures-resine',
    slug: 'fermetures-resine',
    name: 'Fermetures Résine',
    description: 'Fermetures en résine (plastique) robustes et colorées',
    icon: '🎨',
    color: '#8B5CF6',
  },
  {
    id: 'fermetures-metal',
    slug: 'fermetures-metal',
    name: 'Fermetures Métal',
    description: 'Fermetures métalliques laiton et aluminium — haut de gamme',
    icon: '⚙️',
    color: '#D4A843',
  },
  {
    id: 'fermetures-invisibles',
    slug: 'fermetures-invisibles',
    name: 'Fermetures Invisibles',
    description: 'Fermetures invisibles pour robes et vêtements élégants',
    icon: '👗',
    color: '#EC4899',
  },
  {
    id: 'boutons',
    slug: 'boutons',
    name: 'Boutons',
    description: 'Boutons pression, couverts, fantaisie — large gamme',
    icon: '🔘',
    color: '#10B981',
  },
  {
    id: 'elastiques',
    slug: 'elastiques',
    name: 'Élastiques',
    description: 'Élastiques plats, ronds et dentelle pour toutes applications',
    icon: '〰️',
    color: '#F59E0B',
  },
  {
    id: 'biais-rubans',
    slug: 'biais-rubans',
    name: 'Biais & Rubans',
    description: 'Biais coton et rubans satin, gros grain et fantaisie',
    icon: '🎀',
    color: '#C8102E',
  },
  {
    id: 'scratch-velcro',
    slug: 'scratch-velcro',
    name: 'Scratch / Velcro',
    description: 'Bandes auto-agrippantes scratch et velcro toutes largeurs',
    icon: '🪄',
    color: '#06B6D4',
  },
  {
    id: 'accessoires-couture',
    slug: 'accessoires-couture',
    name: 'Accessoires Couture',
    description: 'Aiguilles, épingles, dés à coudre et accessoires mercerie',
    icon: '🧵',
    color: '#F97316',
  },
];

// ─── Placeholder images (using picsum for demo) ───────────────────────────────
// In production, these would be Firebase Storage URLs
const IMG = (id: number, w = 600, h = 600) => `https://picsum.photos/seed/${id}/${w}/${h}`;

// ─── Demo Products ────────────────────────────────────────────────────────────
export const SHOP_PRODUCTS_DATA: ShopProduct[] = [
  // ── FERMETURES NYLON ──────────────────────────────────────────────────────
  {
    id: 'fn-no5-75-noir',
    slug: 'fermeture-nylon-no5-75cm-noir',
    name: 'Fermeture Nylon NO5 — 75cm',
    shortDescription: 'Fermeture éclair nylon NO5, 75cm, disponible en plusieurs couleurs',
    description: 'Fermeture éclair nylon haute qualité numéro 5, longueur 75cm. Idéale pour pantalons, jupes, robes et sacs. Curseur en alliage de zinc résistant. Disponible en noir, blanc, marine, beige et rouge.',
    categorySlug: 'fermetures-nylon',
    categoryName: 'Fermetures Nylon',
    images: [IMG(10), IMG(11), IMG(12)],
    price: 4.5,
    comparePrice: 6,
    sku: 'FN-NO5-75',
    inStock: true,
    stockQty: 1500,
    variants: [
      { id: 'v1', color: 'Noir', colorHex: '#1a1a1a', size: '75cm', stock: 500 },
      { id: 'v2', color: 'Blanc', colorHex: '#ffffff', size: '75cm', stock: 400 },
      { id: 'v3', color: 'Marine', colorHex: '#1e3a5f', size: '75cm', stock: 300 },
      { id: 'v4', color: 'Beige', colorHex: '#d4b896', size: '75cm', stock: 200 },
      { id: 'v5', color: 'Rouge', colorHex: '#C8102E', size: '75cm', stock: 100 },
    ],
    tags: ['nylon', 'no5', 'fermeture', 'pantalon'],
    isFeatured: true,
    isPromo: true,
    rating: 4.7,
    reviewCount: 128,
    specifications: { 'Numéro': 'NO5', 'Longueur': '75cm', 'Matière': 'Nylon', 'Curseur': 'Alliage zinc' },
    weight: 15,
    minOrderQty: 10,
    wholesalePrice: 3.8,
  },
  {
    id: 'fn-no5-120-assort',
    slug: 'fermeture-nylon-no5-120cm',
    name: 'Fermeture Nylon NO5 — 1m20',
    shortDescription: 'Fermeture nylon NO5, 1m20, pour vestes et manteaux',
    description: 'Fermeture éclair nylon numéro 5, longueur 120cm. Parfaite pour vestes, manteaux, sacs et bagages. Glissière fluide et durable.',
    categorySlug: 'fermetures-nylon',
    categoryName: 'Fermetures Nylon',
    images: [IMG(20), IMG(21)],
    price: 6.5,
    sku: 'FN-NO5-120',
    inStock: true,
    stockQty: 800,
    variants: [
      { id: 'v1', color: 'Noir', colorHex: '#1a1a1a', size: '1m20', stock: 300 },
      { id: 'v2', color: 'Blanc', colorHex: '#ffffff', size: '1m20', stock: 250 },
      { id: 'v3', color: 'Marine', colorHex: '#1e3a5f', size: '1m20', stock: 250 },
    ],
    tags: ['nylon', 'no5', 'fermeture', 'veste'],
    isFeatured: false,
    isNew: true,
    rating: 4.5,
    reviewCount: 64,
    specifications: { 'Numéro': 'NO5', 'Longueur': '1m20', 'Matière': 'Nylon' },
    weight: 20,
    minOrderQty: 10,
    wholesalePrice: 5.5,
  },
  {
    id: 'fn-no3-20-assort',
    slug: 'fermeture-nylon-no3-20cm',
    name: 'Fermeture Nylon NO3 — 20cm',
    shortDescription: 'Petite fermeture nylon NO3, 20cm, pour pochettes et accessoires',
    description: 'Fermeture éclair nylon numéro 3, longueur 20cm. Très utilisée pour pochettes, sacs à main, trousses et petits accessoires.',
    categorySlug: 'fermetures-nylon',
    categoryName: 'Fermetures Nylon',
    images: [IMG(30), IMG(31)],
    price: 2.5,
    comparePrice: 3.5,
    sku: 'FN-NO3-20',
    inStock: true,
    stockQty: 2000,
    variants: [
      { id: 'v1', color: 'Noir', colorHex: '#1a1a1a', size: '20cm', stock: 600 },
      { id: 'v2', color: 'Blanc', colorHex: '#ffffff', size: '20cm', stock: 500 },
      { id: 'v3', color: 'Rouge', colorHex: '#C8102E', size: '20cm', stock: 400 },
      { id: 'v4', color: 'Bleu', colorHex: '#3B82F6', size: '20cm', stock: 300 },
      { id: 'v5', color: 'Vert', colorHex: '#10B981', size: '20cm', stock: 200 },
    ],
    tags: ['nylon', 'no3', 'fermeture', 'pochette'],
    isPromo: true,
    rating: 4.6,
    reviewCount: 95,
    specifications: { 'Numéro': 'NO3', 'Longueur': '20cm', 'Matière': 'Nylon' },
    weight: 8,
    minOrderQty: 20,
    wholesalePrice: 2.0,
  },
  {
    id: 'fn-no8-60-noir',
    slug: 'fermeture-nylon-no8-60cm',
    name: 'Fermeture Nylon NO8 — 60cm',
    shortDescription: 'Fermeture nylon NO8 robuste, 60cm, pour bagages et équipements',
    description: 'Fermeture éclair nylon gros calibre numéro 8, longueur 60cm. Haute résistance, idéale pour bagages, sacs de sport, tentes et équipements techniques.',
    categorySlug: 'fermetures-nylon',
    categoryName: 'Fermetures Nylon',
    images: [IMG(40), IMG(41)],
    price: 8.5,
    sku: 'FN-NO8-60',
    inStock: true,
    stockQty: 600,
    variants: [
      { id: 'v1', color: 'Noir', colorHex: '#1a1a1a', size: '60cm', stock: 300 },
      { id: 'v2', color: 'Kaki', colorHex: '#6b7347', size: '60cm', stock: 200 },
      { id: 'v3', color: 'Gris', colorHex: '#9ca3af', size: '60cm', stock: 100 },
    ],
    tags: ['nylon', 'no8', 'fermeture', 'bagage'],
    isFeatured: true,
    rating: 4.8,
    reviewCount: 42,
    specifications: { 'Numéro': 'NO8', 'Longueur': '60cm', 'Résistance': 'Haute' },
    weight: 25,
    minOrderQty: 5,
    wholesalePrice: 7.0,
  },

  // ── FERMETURES RÉSINE ─────────────────────────────────────────────────────
  {
    id: 'fr-no5-35-assort',
    slug: 'fermeture-resine-no5-35cm',
    name: 'Fermeture Résine NO5 — 35cm',
    shortDescription: 'Fermeture résine colorée NO5, 35cm, robuste et légère',
    description: 'Fermeture éclair en résine (plastique) numéro 5, longueur 35cm. Très robuste et légère, disponible dans une vaste gamme de couleurs vives. Parfaite pour vêtements décontractés, enfants et articles de mode.',
    categorySlug: 'fermetures-resine',
    categoryName: 'Fermetures Résine',
    images: [IMG(50), IMG(51), IMG(52)],
    price: 3.5,
    comparePrice: 5,
    sku: 'FR-NO5-35',
    inStock: true,
    stockQty: 1200,
    variants: [
      { id: 'v1', color: 'Noir', colorHex: '#1a1a1a', size: '35cm', stock: 200 },
      { id: 'v2', color: 'Blanc', colorHex: '#ffffff', size: '35cm', stock: 200 },
      { id: 'v3', color: 'Rouge', colorHex: '#ef4444', size: '35cm', stock: 150 },
      { id: 'v4', color: 'Bleu Royal', colorHex: '#1d4ed8', size: '35cm', stock: 150 },
      { id: 'v5', color: 'Rose', colorHex: '#ec4899', size: '35cm', stock: 150 },
      { id: 'v6', color: 'Jaune', colorHex: '#eab308', size: '35cm', stock: 150 },
      { id: 'v7', color: 'Vert', colorHex: '#22c55e', size: '35cm', stock: 100 },
      { id: 'v8', color: 'Orange', colorHex: '#f97316', size: '35cm', stock: 100 },
    ],
    tags: ['résine', 'plastique', 'no5', 'coloré'],
    isFeatured: true,
    isPromo: true,
    rating: 4.5,
    reviewCount: 87,
    specifications: { 'Numéro': 'NO5', 'Longueur': '35cm', 'Matière': 'Résine ABS' },
    weight: 12,
    minOrderQty: 12,
    wholesalePrice: 2.8,
  },
  {
    id: 'fr-no3-20-multicolor',
    slug: 'fermeture-resine-no3-20cm',
    name: 'Fermeture Résine NO3 — 20cm',
    shortDescription: 'Petite fermeture résine NO3, 20cm, ultra colorée',
    description: 'Fermeture éclair résine numéro 3, 20cm. Légère et colorée, parfaite pour petits accessoires, pochettes, enfants et projets DIY.',
    categorySlug: 'fermetures-resine',
    categoryName: 'Fermetures Résine',
    images: [IMG(55), IMG(56)],
    price: 2.0,
    sku: 'FR-NO3-20',
    inStock: true,
    stockQty: 3000,
    variants: [
      { id: 'v1', color: 'Assortis', colorHex: '#d4a843', size: '20cm', stock: 3000 },
    ],
    tags: ['résine', 'no3', 'coloré', 'diy'],
    isNew: true,
    rating: 4.3,
    reviewCount: 56,
    specifications: { 'Numéro': 'NO3', 'Longueur': '20cm', 'Matière': 'Résine' },
    weight: 6,
    minOrderQty: 24,
    wholesalePrice: 1.5,
  },

  // ── FERMETURES MÉTAL ──────────────────────────────────────────────────────
  {
    id: 'fm-no5-20-laiton',
    slug: 'fermeture-metal-no5-20cm-laiton',
    name: 'Fermeture Métal NO5 — 20cm Laiton',
    shortDescription: 'Fermeture métal laiton NO5, 20cm, finition premium',
    description: 'Fermeture éclair métallique en laiton numéro 5, longueur 20cm. Finition dorée élégante, idéale pour jeans, pantalons de luxe, sacs à main et maroquinerie. Résistance exceptionnelle.',
    categorySlug: 'fermetures-metal',
    categoryName: 'Fermetures Métal',
    images: [IMG(60), IMG(61), IMG(62)],
    price: 7.5,
    comparePrice: 10,
    sku: 'FM-NO5-20-L',
    inStock: true,
    stockQty: 500,
    variants: [
      { id: 'v1', color: 'Doré', colorHex: '#D4A843', size: '20cm', stock: 200 },
      { id: 'v2', color: 'Argenté', colorHex: '#9ca3af', size: '20cm', stock: 200 },
      { id: 'v3', color: 'Vieux Laiton', colorHex: '#a16207', size: '20cm', stock: 100 },
    ],
    tags: ['métal', 'laiton', 'no5', 'jean', 'luxe'],
    isFeatured: true,
    rating: 4.9,
    reviewCount: 73,
    specifications: { 'Numéro': 'NO5', 'Longueur': '20cm', 'Matière': 'Laiton', 'Finition': 'Doré/Argenté' },
    weight: 22,
    minOrderQty: 6,
    wholesalePrice: 6.0,
  },
  {
    id: 'fm-no3-15-argent',
    slug: 'fermeture-metal-no3-15cm-argent',
    name: 'Fermeture Métal NO3 — 15cm Argenté',
    shortDescription: 'Élégante fermeture métal argentée NO3, pour sacs et maroquinerie',
    description: 'Fermeture éclair métal argentée numéro 3, 15cm. Très prisée pour la maroquinerie, les pochettes de luxe et les sacs à main.',
    categorySlug: 'fermetures-metal',
    categoryName: 'Fermetures Métal',
    images: [IMG(65), IMG(66)],
    price: 5.5,
    sku: 'FM-NO3-15-A',
    inStock: true,
    stockQty: 700,
    variants: [
      { id: 'v1', color: 'Argenté', colorHex: '#9ca3af', size: '15cm', stock: 400 },
      { id: 'v2', color: 'Doré', colorHex: '#D4A843', size: '15cm', stock: 300 },
    ],
    tags: ['métal', 'argenté', 'no3', 'sac', 'maroquinerie'],
    rating: 4.7,
    reviewCount: 38,
    specifications: { 'Numéro': 'NO3', 'Longueur': '15cm', 'Matière': 'Métal' },
    weight: 18,
    minOrderQty: 10,
    wholesalePrice: 4.5,
  },

  // ── FERMETURES INVISIBLES ─────────────────────────────────────────────────
  {
    id: 'fi-22cm-assort',
    slug: 'fermeture-invisible-22cm',
    name: 'Fermeture Invisible — 22cm',
    shortDescription: 'Fermeture invisible 22cm pour robes et jupes, finition parfaite',
    description: 'Fermeture éclair invisible 22cm. Se dissimule parfaitement dans la couture pour une finition impeccable. Indispensable pour robes de soirée, jupes élégantes et vêtements de qualité.',
    categorySlug: 'fermetures-invisibles',
    categoryName: 'Fermetures Invisibles',
    images: [IMG(70), IMG(71)],
    price: 4.0,
    comparePrice: 5.5,
    sku: 'FI-22',
    inStock: true,
    stockQty: 900,
    variants: [
      { id: 'v1', color: 'Blanc', colorHex: '#f9fafb', size: '22cm', stock: 300 },
      { id: 'v2', color: 'Noir', colorHex: '#1a1a1a', size: '22cm', stock: 300 },
      { id: 'v3', color: 'Beige', colorHex: '#d4b896', size: '22cm', stock: 200 },
      { id: 'v4', color: 'Ivoire', colorHex: '#fffff0', size: '22cm', stock: 100 },
    ],
    tags: ['invisible', 'robe', 'jupe', 'couture', 'élégant'],
    isFeatured: true,
    isPromo: true,
    rating: 4.8,
    reviewCount: 112,
    specifications: { 'Type': 'Invisible', 'Longueur': '22cm', 'Application': 'Couture cachée' },
    weight: 10,
    minOrderQty: 12,
    wholesalePrice: 3.2,
  },
  {
    id: 'fi-25cm-assort',
    slug: 'fermeture-invisible-25cm',
    name: 'Fermeture Invisible — 25cm',
    shortDescription: 'Grande fermeture invisible 25cm, idéale robes longues',
    description: 'Fermeture éclair invisible 25cm. Format plus grand pour robes de mariée, longues robes de soirée et vêtements nécessitant une plus grande ouverture.',
    categorySlug: 'fermetures-invisibles',
    categoryName: 'Fermetures Invisibles',
    images: [IMG(75), IMG(76)],
    price: 4.5,
    sku: 'FI-25',
    inStock: true,
    stockQty: 600,
    variants: [
      { id: 'v1', color: 'Blanc', colorHex: '#f9fafb', size: '25cm', stock: 200 },
      { id: 'v2', color: 'Ivoire', colorHex: '#fffff0', size: '25cm', stock: 200 },
      { id: 'v3', color: 'Noir', colorHex: '#1a1a1a', size: '25cm', stock: 200 },
    ],
    tags: ['invisible', 'mariée', 'robe longue'],
    isNew: true,
    rating: 4.7,
    reviewCount: 45,
    specifications: { 'Type': 'Invisible', 'Longueur': '25cm' },
    weight: 12,
    minOrderQty: 12,
    wholesalePrice: 3.6,
  },

  // ── BOUTONS ───────────────────────────────────────────────────────────────
  {
    id: 'bp-15mm-assort',
    slug: 'bouton-pression-15mm',
    name: 'Bouton Pression — 15mm',
    shortDescription: 'Boutons pression métal 15mm, pack de 50 pièces',
    description: 'Boutons pression en métal nickelé 15mm. Faciles à poser avec pince à riveter. Idéaux pour jeans, vestes, sacs et accessoires cuir. Pack de 50 pièces (boutons + œillets).',
    categorySlug: 'boutons',
    categoryName: 'Boutons',
    images: [IMG(80), IMG(81), IMG(82)],
    price: 22,
    comparePrice: 30,
    sku: 'BP-15-50',
    inStock: true,
    stockQty: 200,
    variants: [
      { id: 'v1', color: 'Argenté', colorHex: '#9ca3af', stock: 80 },
      { id: 'v2', color: 'Doré', colorHex: '#D4A843', stock: 80 },
      { id: 'v3', color: 'Noir', colorHex: '#1a1a1a', stock: 40 },
    ],
    tags: ['bouton', 'pression', 'métal', 'jean'],
    isFeatured: true,
    isPromo: true,
    rating: 4.6,
    reviewCount: 89,
    specifications: { 'Diamètre': '15mm', 'Matière': 'Métal nickelé', 'Quantité': '50 pcs' },
    weight: 150,
    minOrderQty: 1,
    wholesalePrice: 18,
  },
  {
    id: 'bc-20mm-assort',
    slug: 'bouton-couvert-20mm',
    name: 'Bouton Couvert — 20mm',
    shortDescription: 'Kit boutons couverts tissu 20mm, résultat professionnel',
    description: 'Kit boutons couverts à habiller soi-même, 20mm. Permet de créer des boutons assortis à votre tissu. Pack de 30 kits. Outil de pose inclus.',
    categorySlug: 'boutons',
    categoryName: 'Boutons',
    images: [IMG(85), IMG(86)],
    price: 18,
    sku: 'BC-20-30',
    inStock: true,
    stockQty: 150,
    variants: [
      { id: 'v1', color: 'À habiller', colorHex: '#d4b896', stock: 150 },
    ],
    tags: ['bouton', 'couvert', 'tissu', 'diy'],
    isNew: true,
    rating: 4.4,
    reviewCount: 34,
    specifications: { 'Diamètre': '20mm', 'Quantité': '30 kits', 'Outil': 'Inclus' },
    weight: 120,
    minOrderQty: 1,
    wholesalePrice: 14,
  },

  // ── ÉLASTIQUES ────────────────────────────────────────────────────────────
  {
    id: 'el-plat-25mm-5m',
    slug: 'elastique-plat-25mm-5m',
    name: 'Élastique Plat 25mm — Rouleau 5m',
    shortDescription: 'Élastique plat 25mm de largeur, rouleau de 5 mètres',
    description: 'Élastique plat blanc ou noir, largeur 25mm, rouleau de 5 mètres. Résistance élevée, parfait pour ceintures de pantalons, jupes, pyjamas et vêtements de sport.',
    categorySlug: 'elastiques',
    categoryName: 'Élastiques',
    images: [IMG(90), IMG(91)],
    price: 12,
    comparePrice: 16,
    sku: 'EL-P-25-5M',
    inStock: true,
    stockQty: 300,
    variants: [
      { id: 'v1', color: 'Blanc', colorHex: '#ffffff', size: '25mm / 5m', stock: 150 },
      { id: 'v2', color: 'Noir', colorHex: '#1a1a1a', size: '25mm / 5m', stock: 150 },
    ],
    tags: ['élastique', 'plat', 'ceinture', 'pantalon'],
    isFeatured: true,
    isPromo: true,
    rating: 4.7,
    reviewCount: 67,
    specifications: { 'Largeur': '25mm', 'Longueur': '5m', 'Type': 'Plat', 'Matière': 'Polyester/Caoutchouc' },
    weight: 80,
    minOrderQty: 1,
    wholesalePrice: 9.5,
  },
  {
    id: 'el-plat-10mm-10m',
    slug: 'elastique-plat-10mm-10m',
    name: 'Élastique Plat 10mm — Rouleau 10m',
    shortDescription: 'Élastique plat fin 10mm, rouleau 10m, multi-usage',
    description: 'Élastique plat fin 10mm, rouleau de 10 mètres. Usage multiple : sous-vêtements, maillots de bain, taille de pantalons légers. Très élastique et résistant au lavage.',
    categorySlug: 'elastiques',
    categoryName: 'Élastiques',
    images: [IMG(95), IMG(96)],
    price: 14,
    sku: 'EL-P-10-10M',
    inStock: true,
    stockQty: 250,
    variants: [
      { id: 'v1', color: 'Blanc', colorHex: '#ffffff', size: '10mm / 10m', stock: 150 },
      { id: 'v2', color: 'Noir', colorHex: '#1a1a1a', size: '10mm / 10m', stock: 100 },
    ],
    tags: ['élastique', 'fin', 'sous-vêtement'],
    rating: 4.5,
    reviewCount: 42,
    specifications: { 'Largeur': '10mm', 'Longueur': '10m', 'Type': 'Plat fin' },
    weight: 60,
    minOrderQty: 1,
    wholesalePrice: 11,
  },
  {
    id: 'el-dentelle-15mm',
    slug: 'elastique-dentelle-15mm',
    name: 'Élastique Dentelle 15mm',
    shortDescription: 'Élastique dentelle élégant 15mm, plusieurs couleurs',
    description: 'Élastique dentelle décoratif 15mm. Parfait pour lingerie, sous-vêtements, pyjamas et vêtements féminins. Toucher doux, résistant au lavage.',
    categorySlug: 'elastiques',
    categoryName: 'Élastiques',
    images: [IMG(97), IMG(98)],
    price: 16,
    comparePrice: 20,
    sku: 'EL-D-15',
    inStock: true,
    stockQty: 180,
    variants: [
      { id: 'v1', color: 'Blanc', colorHex: '#ffffff', size: '15mm', stock: 60 },
      { id: 'v2', color: 'Noir', colorHex: '#1a1a1a', size: '15mm', stock: 60 },
      { id: 'v3', color: 'Rose', colorHex: '#ec4899', size: '15mm', stock: 60 },
    ],
    tags: ['élastique', 'dentelle', 'lingerie', 'décoratif'],
    isNew: true,
    rating: 4.8,
    reviewCount: 28,
    specifications: { 'Largeur': '15mm', 'Type': 'Dentelle', 'Rouleau': '5m' },
    weight: 40,
    minOrderQty: 2,
    wholesalePrice: 12.5,
  },

  // ── BIAIS & RUBANS ────────────────────────────────────────────────────────
  {
    id: 'bi-coton-18mm-3m',
    slug: 'biais-coton-18mm',
    name: 'Biais Coton — 18mm',
    shortDescription: 'Biais coton replié 18mm, grande gamme de couleurs',
    description: 'Biais coton replié 18mm (largeur déplié 36mm). 100% coton, idéal pour finitions propres sur vêtements, remplacer fermetures, bordures de rideaux et tapisserie. Rouleau de 3 mètres.',
    categorySlug: 'biais-rubans',
    categoryName: 'Biais & Rubans',
    images: [IMG(100), IMG(101), IMG(102)],
    price: 8,
    comparePrice: 11,
    sku: 'BI-CT-18-3M',
    inStock: true,
    stockQty: 400,
    variants: [
      { id: 'v1', color: 'Blanc', colorHex: '#ffffff', stock: 80 },
      { id: 'v2', color: 'Noir', colorHex: '#1a1a1a', stock: 80 },
      { id: 'v3', color: 'Rouge', colorHex: '#C8102E', stock: 60 },
      { id: 'v4', color: 'Marine', colorHex: '#1e3a5f', stock: 60 },
      { id: 'v5', color: 'Beige', colorHex: '#d4b896', stock: 60 },
      { id: 'v6', color: 'Vert', colorHex: '#22c55e', stock: 60 },
    ],
    tags: ['biais', 'coton', 'finition', 'bordure'],
    isFeatured: true,
    isPromo: true,
    rating: 4.7,
    reviewCount: 56,
    specifications: { 'Largeur': '18mm replié', 'Matière': '100% coton', 'Longueur': '3m' },
    weight: 30,
    minOrderQty: 2,
    wholesalePrice: 6.0,
  },
  {
    id: 'ru-satin-25mm-5m',
    slug: 'ruban-satin-25mm',
    name: 'Ruban Satin — 25mm',
    shortDescription: 'Ruban satin brillant 25mm, pour décoration et emballage',
    description: 'Ruban satin brillant double face 25mm, rouleau de 5 mètres. Parfait pour décorations, emballages cadeaux, mariages, confection et couture créative.',
    categorySlug: 'biais-rubans',
    categoryName: 'Biais & Rubans',
    images: [IMG(110), IMG(111)],
    price: 10,
    sku: 'RU-SA-25-5M',
    inStock: true,
    stockQty: 350,
    variants: [
      { id: 'v1', color: 'Blanc', colorHex: '#ffffff', stock: 80 },
      { id: 'v2', color: 'Or', colorHex: '#D4A843', stock: 80 },
      { id: 'v3', color: 'Argent', colorHex: '#9ca3af', stock: 60 },
      { id: 'v4', color: 'Rouge', colorHex: '#C8102E', stock: 60 },
      { id: 'v5', color: 'Rose', colorHex: '#ec4899', stock: 70 },
    ],
    tags: ['ruban', 'satin', 'décoration', 'mariage'],
    isNew: true,
    rating: 4.6,
    reviewCount: 48,
    specifications: { 'Largeur': '25mm', 'Matière': 'Satin polyester', 'Longueur': '5m' },
    weight: 25,
    minOrderQty: 2,
    wholesalePrice: 7.5,
  },

  // ── SCRATCH / VELCRO ──────────────────────────────────────────────────────
  {
    id: 'sc-20mm-blanc-1m',
    slug: 'scratch-velcro-20mm-1m',
    name: 'Scratch Auto-Agrippant — 20mm',
    shortDescription: 'Bande scratch 20mm blanc ou noir, rouleau 1 mètre',
    description: 'Bande scratch (velcro) auto-agrippante 20mm, rouleau de 1 mètre. Comprend les deux faces (crochet + boucle). Idéal pour vêtements, sacs, chaussures et DIY. Lavable.',
    categorySlug: 'scratch-velcro',
    categoryName: 'Scratch / Velcro',
    images: [IMG(120), IMG(121)],
    price: 9,
    comparePrice: 12,
    sku: 'SC-20-1M',
    inStock: true,
    stockQty: 400,
    variants: [
      { id: 'v1', color: 'Blanc', colorHex: '#ffffff', size: '20mm', stock: 200 },
      { id: 'v2', color: 'Noir', colorHex: '#1a1a1a', size: '20mm', stock: 200 },
    ],
    tags: ['scratch', 'velcro', 'auto-agrippant', 'fermeture'],
    isFeatured: true,
    isPromo: true,
    rating: 4.6,
    reviewCount: 74,
    specifications: { 'Largeur': '20mm', 'Longueur': '1m', 'Type': 'Crochet + boucle' },
    weight: 35,
    minOrderQty: 2,
    wholesalePrice: 7.0,
  },
  {
    id: 'sc-50mm-noir-1m',
    slug: 'scratch-velcro-50mm-1m',
    name: 'Scratch Auto-Agrippant Large — 50mm',
    shortDescription: 'Grande bande scratch 50mm, résistance maximale',
    description: 'Bande scratch large 50mm, rouleau de 1 mètre. Double face. Résistance maximale pour applications lourdes : équipements sportifs, valises, panneaux de velcro, stores.',
    categorySlug: 'scratch-velcro',
    categoryName: 'Scratch / Velcro',
    images: [IMG(125), IMG(126)],
    price: 15,
    sku: 'SC-50-1M',
    inStock: true,
    stockQty: 200,
    variants: [
      { id: 'v1', color: 'Noir', colorHex: '#1a1a1a', size: '50mm', stock: 120 },
      { id: 'v2', color: 'Blanc', colorHex: '#ffffff', size: '50mm', stock: 80 },
    ],
    tags: ['scratch', 'velcro', 'large', 'robuste'],
    rating: 4.7,
    reviewCount: 29,
    specifications: { 'Largeur': '50mm', 'Longueur': '1m', 'Résistance': 'Haute' },
    weight: 65,
    minOrderQty: 2,
    wholesalePrice: 12.0,
  },

  // ── ACCESSOIRES COUTURE ───────────────────────────────────────────────────
  {
    id: 'ac-aiguilles-asst',
    slug: 'kit-aiguilles-couture',
    name: 'Kit Aiguilles Couture — 30 pcs',
    shortDescription: 'Set de 30 aiguilles couture main, toutes tailles',
    description: 'Kit professionnel de 30 aiguilles couture main, différentes tailles (N°3 à N°9). Acier inoxydable nickelé, pointu et solide. Rangement pratique dans étui rigide.',
    categorySlug: 'accessoires-couture',
    categoryName: 'Accessoires Couture',
    images: [IMG(130), IMG(131)],
    price: 15,
    comparePrice: 20,
    sku: 'AC-AGU-30',
    inStock: true,
    stockQty: 200,
    variants: [
      { id: 'v1', color: 'Argenté', colorHex: '#9ca3af', stock: 200 },
    ],
    tags: ['aiguilles', 'couture', 'kit', 'main'],
    rating: 4.5,
    reviewCount: 43,
    specifications: { 'Quantité': '30 pcs', 'Tailles': 'N°3 à N°9', 'Matière': 'Acier nickelé' },
    weight: 40,
    minOrderQty: 1,
    wholesalePrice: 11,
  },
  {
    id: 'ac-de-metal',
    slug: 'de-a-coudre-metal',
    name: 'Dé à Coudre Métal — Taille M',
    shortDescription: 'Dé à coudre en métal solide, protection doigt',
    description: 'Dé à coudre professionnel en métal (aluminium). Protège le doigt lors de la couture main. Taille M standard, confortable. Finition soignée.',
    categorySlug: 'accessoires-couture',
    categoryName: 'Accessoires Couture',
    images: [IMG(135), IMG(136)],
    price: 6,
    sku: 'AC-DE-M',
    inStock: true,
    stockQty: 300,
    variants: [
      { id: 'v1', color: 'Argenté', colorHex: '#9ca3af', stock: 150 },
      { id: 'v2', color: 'Doré', colorHex: '#D4A843', stock: 150 },
    ],
    tags: ['dé', 'couture', 'protection', 'métal'],
    rating: 4.3,
    reviewCount: 22,
    specifications: { 'Taille': 'M', 'Matière': 'Aluminium' },
    weight: 12,
    minOrderQty: 1,
    wholesalePrice: 4.5,
  },
  {
    id: 'ac-epingles-100',
    slug: 'epingles-couture-100pcs',
    name: 'Épingles Couture — 100 pcs',
    shortDescription: '100 épingles couture acier inoxydable, boîte plastique',
    description: 'Lot de 100 épingles couture en acier inoxydable, 3cm. Pointes très fines, ne rouillent pas. Idéales pour assembler tissu, patron et travaux couture. Boîte de rangement incluse.',
    categorySlug: 'accessoires-couture',
    categoryName: 'Accessoires Couture',
    images: [IMG(140), IMG(141)],
    price: 12,
    sku: 'AC-EPI-100',
    inStock: true,
    stockQty: 250,
    variants: [
      { id: 'v1', color: 'Argenté', colorHex: '#9ca3af', stock: 250 },
    ],
    tags: ['épingles', 'couture', 'assemblage', 'acier'],
    isFeatured: false,
    isNew: false,
    rating: 4.6,
    reviewCount: 58,
    specifications: { 'Quantité': '100 pcs', 'Longueur': '3cm', 'Matière': 'Acier inox' },
    weight: 50,
    minOrderQty: 1,
    wholesalePrice: 9.0,
  },
];

// Helper functions
export function getProductById(id: string): ShopProduct | undefined {
  return SHOP_PRODUCTS_DATA.find(p => p.id === id);
}

export function getProductBySlug(slug: string): ShopProduct | undefined {
  return SHOP_PRODUCTS_DATA.find(p => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): ShopProduct[] {
  return SHOP_PRODUCTS_DATA.filter(p => p.categorySlug === categorySlug);
}

export function getFeaturedProducts(limit = 8): ShopProduct[] {
  return SHOP_PRODUCTS_DATA.filter(p => p.isFeatured).slice(0, limit);
}

export function getNewProducts(limit = 6): ShopProduct[] {
  return SHOP_PRODUCTS_DATA.filter(p => p.isNew).slice(0, limit);
}

export function getPromoProducts(limit = 6): ShopProduct[] {
  return SHOP_PRODUCTS_DATA.filter(p => p.isPromo && p.comparePrice).slice(0, limit);
}

export function getSimilarProducts(product: ShopProduct, limit = 4): ShopProduct[] {
  return SHOP_PRODUCTS_DATA
    .filter(p => p.id !== product.id && p.categorySlug === product.categorySlug)
    .slice(0, limit);
}

export function searchProducts(query: string): ShopProduct[] {
  if (!query.trim()) return SHOP_PRODUCTS_DATA;
  const q = query.toLowerCase();
  return SHOP_PRODUCTS_DATA.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.categoryName?.toLowerCase().includes(q) ||
    p.tags.some(t => t.includes(q))
  );
}

export function getCategoryById(slug: string): ShopCategory | undefined {
  return SHOP_CATEGORIES.find(c => c.slug === slug);
}
