// ─── Curated Items for Temu-style Mega Menu ───────────────────────────────────

export interface MegaItem {
  id: string;
  name: string;
  nameAr: string;
  href?: string;
  image?: string;
  isHot?: boolean;
}

export const MEGA_MENU_CURATED_DATA: Record<string, MegaItem[]> = {
  'fermetures-nylon': [
    {
      id: 'nylon-3-inv',
      name: 'Nylon N°3 Invisible',
      nameAr: 'سحاب نايلون 3 خفي',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'nylon-5-sep',
      name: 'Nylon N°5 Séparable',
      nameAr: 'نايلون 5 قابل للفصل',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'nylon-5-non-sep',
      name: 'Nylon Non Séparable',
      nameAr: 'نايلون غير قابل للفصل',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'nylon-rouleau',
      name: 'Au Mètre & Rouleau',
      nameAr: 'بالمتر وبالرول',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'nylon-curseurs',
      name: 'Curseurs N°3 & N°5',
      nameAr: 'منزلقات نايلون 3 و 5',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'nylon-spirale',
      name: 'Spirale Fine 20-60cm',
      nameAr: 'سحاب لولبي رفيع',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'nylon-double-sens',
      name: 'Fermeture Double Sens',
      nameAr: 'سحاب اتجاهين',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'nylon-assortiments',
      name: 'Lots & Assortiments',
      nameAr: 'مجموعات وتشكيلات',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'nylon-dentelle',
      name: 'Fermeture Dentelle',
      nameAr: 'سحاب دانتيل زينة',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'nylon-tirettes',
      name: 'Tirettes & Cordons',
      nameAr: 'مقابض ومشدات',
      isHot: true,
      image: '/fermetures.jpg',
    },
  ],

  'fermetures-resine': [
    {
      id: 'resine-5',
      name: 'Résine Dents Plastique N°5',
      nameAr: 'بلاستيك أسنان رقم 5',
      isHot: true,
      image: '/fermetures-plastique.jpg',
    },
    {
      id: 'resine-8',
      name: 'Résine Grosse Maille N°8',
      nameAr: 'بلاستيك عريض رقم 8',
      isHot: true,
      image: '/fermetures-plastique.jpg',
    },
    {
      id: 'resine-sport',
      name: 'Blouson & Vêtements Sport',
      nameAr: 'سترات وملابس رياضية',
      isHot: false,
      image: '/fermetures-plastique.jpg',
    },
    {
      id: 'resine-double-curseur',
      name: 'Résine Double Curseur',
      nameAr: 'منزلق مزدوج بلاستيك',
      isHot: true,
      image: '/fermetures-plastique.jpg',
    },
    {
      id: 'resine-curseurs',
      name: 'Curseurs Résine & Plastique',
      nameAr: 'منزلقات بلاستيك ملونة',
      isHot: false,
      image: '/fermetures-plastique.jpg',
    },
    {
      id: 'resine-etanche',
      name: 'Fermeture Étanche / Waterproof',
      nameAr: 'سحاب مقاوم للماء',
      isHot: true,
      image: '/fermetures-plastique.jpg',
    },
    {
      id: 'resine-enfant',
      name: 'Coloris Enfant & Flash',
      nameAr: 'ألوان زاهية للأطفال',
      isHot: false,
      image: '/fermetures-plastique.jpg',
    },
    {
      id: 'resine-sep',
      name: 'Résine Séparable 60-80cm',
      nameAr: 'بلاستيك قابل للفصل',
      isHot: false,
      image: '/fermetures-plastique.jpg',
    },
  ],

  'fermetures-metal': [
    {
      id: 'metal-laiton',
      name: 'Métal Laiton Doré N°5',
      nameAr: 'نحاس ذهبي رقم 5',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'metal-bronze',
      name: 'Métal Bronze Antique',
      nameAr: 'برونز كلاسيكي معتق',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'metal-argente',
      name: 'Métal Argenté / Nickel',
      nameAr: 'نيكل وفضي لامع',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'metal-jeans',
      name: 'Spécial Jean & Denim N°4',
      nameAr: 'جينز ودنيم مقوى',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'metal-cuir',
      name: 'Cuir & Maroquinerie',
      nameAr: 'جلديات وحقائب فاخرة',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'metal-sep',
      name: 'Métal Séparable 60-70cm',
      nameAr: 'معدني قابل للفصل',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'metal-curseurs',
      name: 'Curseurs Métal Renforcés',
      nameAr: 'منزلقات معدنية قوية',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'metal-pantalon',
      name: 'Fermetures Pantalon Métal',
      nameAr: 'سحابات سراويل معدنية',
      isHot: false,
      image: '/fermetures.jpg',
    },
  ],

  'fermetures-invisibles': [
    {
      id: 'inv-robe',
      name: 'Invisible Robe 22-60cm',
      nameAr: 'خفي لفساتين السهرة',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'inv-jupe',
      name: 'Invisible Jupe & Pantalon',
      nameAr: 'خفي للتنانير والملابس',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'inv-couture',
      name: 'Haute Couture & Soie',
      nameAr: 'خياطة راقية وحرير',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'inv-curseur',
      name: 'Curseur Goutte Discret',
      nameAr: 'منزلق قطرة أنيق',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'inv-pied',
      name: 'Pied Presseur Invisible',
      nameAr: 'دواسة سحاب خفي',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'inv-nuancier',
      name: 'Nuancier Grand Choix Couleurs',
      nameAr: 'تشكيلة ألوان شاملة',
      isHot: false,
      image: '/fermetures.jpg',
    },
  ],

  'boutons': [
    {
      id: 'btn-pression',
      name: 'Boutons Pression Métal',
      nameAr: 'أزرار كبس معدنية',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'btn-chemise',
      name: 'Boutons Chemise Nacre',
      nameAr: 'أزرار قمصان صدفية',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'btn-manteau',
      name: 'Boutons Manteau & Veste',
      nameAr: 'أزرار معاطف وبدل',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'btn-recouvrir',
      name: 'Boutons à Recouvrir',
      nameAr: 'أزرار للتغطية بالقماش',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'btn-bois',
      name: 'Boutons Bois & Naturels',
      nameAr: 'أزرار خشبية طبيعية',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'btn-jeans',
      name: 'Boutons Jeans & Rivets',
      nameAr: 'أزرار جينز ومسامير',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'btn-fantaisie',
      name: 'Boutons Strass & Fantaisie',
      nameAr: 'أزرار كريستال وفخمة',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'btn-enfant',
      name: 'Boutons Enfants Figurines',
      nameAr: 'أزرار أشكال للأطفال',
      isHot: false,
      image: '/fermetures.jpg',
    },
  ],

  'elastiques': [
    {
      id: 'elast-plat',
      name: 'Élastique Plat Tissé Blanc/Noir',
      nameAr: 'مطاط مسطح أبيض وأسود',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'elast-large',
      name: 'Bande Élastique Large 40-50mm',
      nameAr: 'شريط مطاطي عريض 40-50 مم',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'elast-rond',
      name: 'Élastique Rond & Masque',
      nameAr: 'مطاط دائري رفيع',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'elast-boutonniere',
      name: 'Élastique Boutonnière Enfant',
      nameAr: 'مطاط بعيون أزرار',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'elast-lingerie',
      name: 'Élastique Lingerie & Dentelle',
      nameAr: 'مطاط ملابس ناعم',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'elast-lurex',
      name: 'Élastique Lurex Brillant',
      nameAr: 'مطاط لوريكس لامع',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'elast-rouleau',
      name: 'Rouleaux Gros Métrage',
      nameAr: 'بكرات مطاط بالجملة',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'elast-cordon',
      name: 'Cordon Élastique Cordonnet',
      nameAr: 'حبل مطاطي متين',
      isHot: false,
      image: '/fermetures.jpg',
    },
  ],

  'biais-rubans': [
    {
      id: 'biais-coton',
      name: 'Biais Coton Plié 20mm',
      nameAr: 'شريط بيه قطن مطوي 20 مم',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'ruban-satin',
      name: 'Ruban Satin Simple & Double',
      nameAr: 'شريط ساتان لامع فاخر',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'ruban-gros-grain',
      name: 'Ruban Gros Grain Texturé',
      nameAr: 'شريط مضلع غروغرين',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'passepoil',
      name: 'Passepoil Coton Décoratif',
      nameAr: 'شريط قيطان وزركشة',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'ruban-serge',
      name: 'Ruban Sergé & Renfort',
      nameAr: 'شريط تويل مقوى',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'dentelle',
      name: 'Dentelle Décorative & Guipure',
      nameAr: 'دانتيل مطرز وغيبور',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'biais-imprime',
      name: 'Biais Fantaisie & Motifs',
      nameAr: 'شريط بيه مزخرف بنقوش',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'ruban-velours',
      name: 'Ruban Velours & Fêtes',
      nameAr: 'شريط مخمل فاخر',
      isHot: false,
      image: '/fermetures.jpg',
    },
  ],

  'scratch-velcro': [
    {
      id: 'velcro-adhesif',
      name: 'Velcro Adhésif Autocollant',
      nameAr: 'فيلكرو لاصق ذاتياً',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'velcro-coudre',
      name: 'Velcro Standard à Coudre',
      nameAr: 'فيلكرو خياطة كلاسيكي',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'velcro-20mm',
      name: 'Bande Agrippante 20mm',
      nameAr: 'شريط لاصق عرض 20 مم',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'velcro-50mm',
      name: 'Bande Agrippante 50mm Large',
      nameAr: 'شريط لاصق عريض 50 مم',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'velcro-pastilles',
      name: 'Pastilles & Cercles Scratch',
      nameAr: 'دوائر فيلكرو لاصقة',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'velcro-cables',
      name: 'Velcro Attache-Câbles',
      nameAr: 'روابط فيلكرو للأسلاك',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'velcro-fort',
      name: 'Velcro Industriel Haute Fixation',
      nameAr: 'فيلكرو قوي جداً صناعي',
      isHot: true,
      image: '/fermetures.jpg',
    },
  ],

  'accessoires-couture': [
    {
      id: 'acc-aiguilles',
      name: 'Aiguilles Machine & Main',
      nameAr: 'إبر ماكينة وإبر يدوية',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'acc-ciseaux',
      name: 'Ciseaux Tailleur Pro',
      nameAr: 'مقصات خياط احترافية',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'acc-metre',
      name: 'Mètre Ruban & Règles',
      nameAr: 'أشرطة قياس ومساطر',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'acc-craie',
      name: 'Craie & Marqueur Tissu',
      nameAr: 'طباشير تحديد القماش',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'acc-epingles',
      name: 'Épingles Tête Perlée',
      nameAr: 'دبابيس برؤوس لؤلؤية',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'acc-decoud-vite',
      name: 'Découd-Vite Ergonomique',
      nameAr: 'فتاقة خيوط سريعة',
      isHot: true,
      image: '/fermetures.jpg',
    },
    {
      id: 'acc-de',
      name: 'Dé à Coudre Métal',
      nameAr: 'كشتبان خياطة معدني',
      isHot: false,
      image: '/fermetures.jpg',
    },
    {
      id: 'acc-enfile',
      name: 'Enfile-Aiguille Rapide',
      nameAr: 'لضامة إبر سريعة',
      isHot: false,
      image: '/fermetures.jpg',
    },
  ],
};
